/* Project Euler #45
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 * Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
 * Pentagonal       Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
 * Hexagonal        Hn=n(2n−1)      1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

#include <iostream>

long tri(long n)
{
    return n*(n+1)/2;
}

long pent(long n)
{
    return n*(3*n-1)/2;
}

long hex(long n)
{
    return n*(2*n-1);
}

int main()
{
    long ti = 285;
    long pi = 165;
    long hi = 143;
    long t, p, h;

    for (hi++;; hi++) {
        h = hex(hi);

        p = pent(pi);
        for (; p < h; pi++) {
            p = pent(pi);
        }
        if (p > h) continue;

        t = tri(ti);
        for (; t < p; ti++) {
            t = tri(ti);
        }

        if (t == p) break;
    }

    std::cout << t << std::endl;

    return 0;
}
